In [2]:
import pandas as pd
df=pd.read_csv("diabetes (1).csv")
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [4]:
X=df.iloc[:,0:8]
y=df.iloc[:, -1]

In [5]:
X

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [6]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [7]:
X.shape

(768, 8)

In [8]:
y.shape

(768,)

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=42)


In [10]:
print(X_train.shape)
print(X_test.shape)

(614, 8)
(154, 8)


In [12]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

In [13]:
reg.fit(X_train,y_train)

LinearRegression()

In [14]:
y_pred=reg.predict(X_test)

In [16]:
from sklearn.metrics import r2_score

In [17]:
r2_score(y_test,y_pred)

0.25500281176741757

In [18]:
reg.coef_

array([ 0.01046818,  0.00563353, -0.00228103,  0.00053209, -0.00027815,
        0.01503864,  0.11126264,  0.00646027])

In [19]:
reg.intercept_

np.float64(-0.9487546338208503)

In [32]:
import numpy as np
class MyLR:
  def __init__(self):
    self.coef=None
    self.intercept=None

  def fit(self,X_train,y_train):
    X_train=np.insert(X_train,0,1,axis=1)
    betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.intercept_=betas[0]
    self.coef_=betas[1:]
    print(betas)

  def predict(self,X_test):
    y_pred=np.dot(X_test,self.coef_)+self.intercept_
    return y_pred


In [33]:
ML=MyLR()

In [34]:
ML.fit(X_train,y_train)

[-9.48754634e-01  1.04681792e-02  5.63352920e-03 -2.28102989e-03
  5.32093401e-04 -2.78145126e-04  1.50386406e-02  1.11262645e-01
  6.46026705e-03]


In [35]:
y_pred=ML.predict(X_test)

array([ 0.33550028,  0.23809869,  0.1510522 ,  0.2401365 ,  0.48142376,
        0.45257375, -0.17450469,  0.60662287,  0.52417796,  0.70476953,
        0.32360466,  0.85290601,  0.38466612,  0.36056948,  0.09946712,
        0.41539557,  0.17869123,  0.07782301,  0.80730861,  0.51299477,
        0.28090594,  0.08303057,  0.5099157 ,  0.11381771,  0.51325022,
        0.82528549,  0.17892718, -0.0594202 ,  0.28338572,  0.16407949,
        0.83851225,  0.80737515,  0.68154389,  0.7649502 ,  0.56140297,
        0.62123131,  1.06134554,  0.30990775,  0.51752336,  0.63691482,
        0.07075333,  0.57757007,  0.55015462,  0.37541745, -0.07644182,
        0.50119208,  0.59600162,  0.27464761,  0.42477995,  0.9941898 ,
        0.00969584,  0.61763578,  0.73395288,  0.31090975,  0.13456812,
       -0.02536316,  0.71219147, -0.30518218,  0.41994556,  0.67869594,
        0.66891428,  0.3798452 ,  0.2956646 ,  0.288035  ,  0.06813053,
        0.55464338,  0.01368504,  0.6272007 , -0.02033281,  0.63

In [36]:
from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

0.25500281176741757

In [37]:
ML.coef_

array([ 0.01046818,  0.00563353, -0.00228103,  0.00053209, -0.00027815,
        0.01503864,  0.11126264,  0.00646027])

In [38]:
ML.intercept_

np.float64(-0.9487546338208567)